name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo apt-get update
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: bundle install 
    - run: docker run -d -e POSTGRES_PASSWORD=password --name my_postgres -p 5432:5432 postgres
    - run:  docker exec -it my_postgres psql -U postgres -c "create database my_database"
    - run: 'DATABASE_URL=postgres://postgres:password@localhost:5432/postgres bundle exec ruby test.rb'
